name: immich_mobile
description: Immich - selfhosted backup media file on mobile phone

publish_to: "none"
version: 1.93.3+119
isar_version: &isar_version 3.1.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  path_provider_ios:
  photo_manager: ^2.7.2
  flutter_hooks: ^0.20.3
  hooks_riverpod: ^2.4.0
  riverpod_annotation: ^2.3.0
  cached_network_image: ^3.2.2
  flutter_cache_manager: ^3.3.0
  intl: ^0.18.0
  auto_route: ^7.0.0
  fluttertoast: ^8.2.2
  video_player: ^2.2.18
  chewie: ^1.4.0
  socket_io_client: ^2.0.0-beta.4-nullsafety.0
  # Update it to tag once next stable release
  maplibre_gl:
      git:
        url: https://github.com/maplibre/flutter-maplibre-gl.git
        ref: acb428a005efd9832a0a8e7ef0945f899dfb3ca5
  geolocator: ^10.0.0 # used to move to current location in map view
  flutter_udid: ^2.0.0
  package_info_plus: ^4.1.0
  url_launcher: ^6.1.3
  http: 0.13.5
  cancellation_token_http: ^1.1.0
  easy_localization: ^3.0.1
  share_plus: ^7.1.0
  flutter_displaymode: ^0.4.0
  scrollable_positioned_list: ^0.3.8
  path: ^1.8.1
  path_provider: ^2.0.11
  collection: ^1.16.0
  http_parser: ^4.0.1
  flutter_web_auth: ^0.5.0
  easy_image_viewer: ^1.2.0
  isar: *isar_version
  isar_flutter_libs: *isar_version # contains Isar Core
  permission_handler: ^10.2.0
  device_info_plus: ^8.1.0
  connectivity_plus: ^4.0.1
  wakelock_plus: ^1.1.1
  flutter_local_notifications: ^15.1.0+1
  timezone: ^0.9.2

  openapi:
    path: openapi

  # easy to remove packages:
  image_picker: ^0.8.5+3 # only used to select user profile image from system gallery -> we can simply select an image from within immich?
  logging: ^1.1.0

# This is uncommented in F-Droid build script
# Taken from https://github.com/Myzel394/locus/blob/445013d22ec1d759027d4303bd65b30c5c8588c8/pubspec.yaml#L105
#fdependency_overrides:
#f  geolocator_android:
#f    git:
#f      url: https://github.com/Zverik/flutter-geolocator.git
#f      ref: floss
#f      path: geolocator_android

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  build_runner: ^2.2.1
  auto_route_generator: ^7.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.2.16
  isar_generator: *isar_version
  integration_test:
    sdk: flutter
  custom_lint: ^0.5.6
  riverpod_lint: ^2.1.0
  riverpod_generator: ^2.3.3
  mocktail: ^1.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/i18n/
  fonts:
    - family: SnowburstOne
      fonts:
        - asset: fonts/SnowburstOne.ttf
    - family: Inconsolata
      fonts:
        - asset: fonts/Inconsolata-Regular.ttf
    - family: Overpass
      fonts:
        - asset: fonts/overpass/Overpass-Regular.ttf
          weight: 400
        - asset: fonts/overpass/Overpass-Italic.ttf
          style: italic
        - asset: fonts/overpass/Overpass-Medium.ttf
          weight: 500
        - asset: fonts/overpass/Overpass-SemiBold.ttf
          weight: 600
        - asset: fonts/overpass/Overpass-Bold.ttf
          weight: 700
    - family: OverpassMono
      fonts:
        - asset: fonts/overpass/OverpassMono.ttf

flutter_launcher_icons:
  image_path_android: "assets/immich-logo-no-outline.png"
  image_path_ios: "assets/immich-logo-no-outline.png"
  android: true # can specify file name here e.g. "ic_launcher"
  ios: true # can specify file name here e.g. "My-Launcher-Icon
  remove_alpha_ios: true

analyzer:
  exclude:
    - openapi/**
